// TD.hx generated by yaml2hx from api.yaml file models (definitions) (see run.sh)
import TD;

class EmployeeDecorator { 
    public static function decorate(b : Employee): Employee { 
        b.LastName+=' :)'; // sample use
        return b; 
    }
}

class IdentityDecorator { 
    public static function decorate(t : Dynamic): Dynamic { 
        return t; 
    }
}